<?php
/**
 * @var $block \Conversify\ScriptManager\Block\CfyData
 */
?>
<!-- Start Conversify page data -->
<script type="text/javascript">
    Conversify = window.Conversify || [];
    try {
        _cfy_data = JSON.parse(atob('<?php echo base64_encode(json_encode($block->getModelData())); ?>'));
        for (k in _cfy_data) {
            console.log(k);
            if (k == 'conversion') {
                Conversify.push(["trackConversion", "default", _cfy_data[k]]);
            } else {
                Conversify[k] = _cfy_data[k];
            }
        }
    } catch ($e) {}

    // data set, require script
    require(['cfybase'], function(cfybase) {
        return {};
    });

</script>
<!-- End Conversify page data -->
