<?php
/**
 * @var $block \Conversify\ScriptManager\Block\CfyCode
 */
?>
<!-- Conversify API code -->
<script type="text/javascript">
    Conversify = window.Conversify || [];
    Conversify.api_key = <?php echo "'".$block->getApiKey()."'" ?>;

    require.config({
        paths: {
            cfybase: <?php echo "'//js.conversify.com/v2/".$block->getApiKey()."'"?>
        }
    });
</script>
<!-- End Conversify API code -->
